modules:
  index:
    path: %path.modules%index/
    menu_path: ~
    action_class: IndexAction
    module_class: IndexModule
    name: Главная страница
    smarty:
      template: %modules.index.path%template/
      compile: %path.smarty.compile%
  usergroups:
    path: %path.modules%usergroups/
    menu_path: Администрирование/Группы пользователей
    action_class: UserGroupsAction
    module_class: UserGroupsModule
    icon: package.png
    name: Группы пользователей
    access:
      enable: true
      acl: [alc_user_groups]
    smarty:
      template: %modules.usergroups.path%template/
      compile: %path.smarty.compile%
  sites:
    path: %path.modules%sites/
    menu_path: ~
    action_class: SitesAction
    module_class: SitesModule
    icon: package.png
    name: Сайты сети
    access:
      enable: true
      acl: [alc_sites]
    smarty:
      template: %modules.sites.path%template/
      compile: %path.smarty.compile%
  users:
    path: %path.modules%users/
    menu_path: Администрирование/Пользователи
    action_class: UsersAction
    module_class: UsersModule
    name: Пользователи
    icon: vcard.png
    access:
      enable: true
      acl:
        index: [acl_user_show, acl_user_edit]
        edit: [acl_user_edit]
        delete: [acl_user_edit]
        save: [acl_user_edit]
    smarty:
      template: %modules.users.path%template/
      compile: %path.smarty.compile%
  pages:
    path: %path.modules%pages/
    menu_path: Содержание/Управление страницами
    action_class: PagesAction
    module_class: PagesModule
    icon: page_code.png
    name: Управление страницами
    params:
      app: frontend
    access:
      enable: true
      acl: [acl_pages]
    smarty:
      template: %modules.pages.path%template/
      compile: %path.smarty.compile%
  login:
    path: %path.modules%login/
    menu_path: ~
    action_class: LoginAction
    module_class: LoginModule
    name: вход в систему
    smarty:
      template: %modules.login.path%template/
      compile: %path.smarty.compile%
  menu:
    path: %path.modules%menu/
    menu_path: ~
    action_class: MenuAction
    module_class: MenuModule
    name: Главное меню
    smarty:
      template: %modules.menu.path%template/
      compile: %path.smarty.compile%
      
  staticpages:
    path: %path.modules%staticpages/
    menu_path: Содержание/Статические страницы
    action_class: StaticPagesAction
    module_class: StaticPagesModule
    icon: page_edit.png
    name: Статтические страницы
    access:
      enable: true
      acl: [acl_static_pages]
    smarty:
      template: %modules.staticpages.path%template/
      compile: %path.smarty.compile%
      
  logview:
    path: %path.modules%logview/
    menu_path: Администрирование/Просмотр лога
    action_class: LogViewAction
    module_class: LogViewModule
    name: Просмотр лога
    icon: report.png
    pager:
      show_per_page: 15;
    access:
      enable: true
      acl: [acl_logview]
    smarty:
      template: %modules.logview.path%template/
      compile: %path.smarty.compile% 
      
<?php /* Транслитерация */ ?>      
  transliterate:
    path: %path.modules%transliterate/
    menu_path: Переводы/Переводы интерфейсов
    action_class: TransliterateAction
    module_class: TransliterateModule
    name: Переводы интерфейсов 
    icon: report.png
    access:
      enable: false
    smarty:
      template: %modules.transliterate.path%template/
      compile: %path.smarty.compile%      
      
<?php /* Новости */ ?>            
  news:
    path: %path.modules%news/
    menu_path: Наполнение/ Новости
    action_class: NewsAction
    module_class: NewsModule
    name: Наполнение/ Новости
    icon: report.png
    pager:
      show_per_page: 15;
    access:
      enable: true
      acl: [acl_news]
    smarty:          
      template: %modules.news.path%template/
      compile: %path.smarty.compile%                  
      
  menu:
    path: %path.modules%menu/
    menu_path: Содержание/Меню
    action_class: MenuAction
    module_class: MenuModule
    name: Меню
    icon: report.png
    smarty:
      template: %modules.menu.path%template/
      compile: %path.smarty.compile%      
      
  feedback:
    path: %path.modules%feedback/
    menu_path: Администрирование/Форма обратной связи
    action_class: FeedbackAction
    module_class: FeedbackModule
    name: Форма обратной связи
    icon: report.png
    smarty:
      template: %modules.feedback.path%template/
      compile: %path.smarty.compile%
            
  advertise:
    path: %path.modules%advertise/
    menu_path: Содержание/Центральный промоблок
    action_class: AdvertiseAction
    module_class: AdvertiseModule
    name: Центральный промоблок
    icon: report.png
    pager:
      show_per_page: 35;
    access:
      enable: true
      acl: [acl_advertise]
    smarty:
      template: %modules.advertise.path%template/
      compile:  %path.smarty.compile%
      
  partner:
    path: %path.modules%partner/
    menu_path: Содержание/Блок "Партнёры"
    action_class: PartnerAction
    module_class: PartnerModule
    name: Блок "Партнёры" 
    icon: report.png
    pager:
      show_per_page: 35;
    access:
      enable: true
      acl: [acl_partner]
    smarty:
      template: %modules.partner.path%template/
      compile:  %path.smarty.compile%
      
  presscentre:
    path: %path.modules%presscentre/
    menu_path: Содержание/Блок "Пресс-центр"
    action_class: PresscentreAction
    module_class: PresscentreModule
    name: Блок "Пресс-центр" 
    icon: report.png
    pager:
      show_per_page: 35;
    access:
      enable: true
      acl: [acl_presscentre]
    smarty:
      template: %modules.presscentre.path%template/
      compile:  %path.smarty.compile%
      
  project:
    path: %path.modules%project/
    menu_path: Содержание/Проекты
    action_class: ProjectAction
    module_class: ProjectModule
    name: Проекты
    icon: report.png
    pager:
      show_per_page: 35;
    access:
      enable: true
      acl: [acl_project]
    smarty:
      template: %modules.project.path%template/
      compile:  %path.smarty.compile%      
      
  service:
    path: %path.modules%service/
    menu_path: Содержание/Услуги
    action_class: ServiceAction
    module_class: ServiceModule
    name: Услуги
    icon: report.png
    pager:
      show_per_page: 35;
    access:
      enable: true
      acl: [acl_service]
    smarty:
      template: %modules.service.path%template/
      compile:  %path.smarty.compile%            
      
  solution:
    path: %path.modules%solution/
    menu_path: Содержание/Решения
    action_class: SolutionAction
    module_class: SolutionModule
    name: Решения
    icon: report.png
    pager:
      show_per_page: 35;
    access:
      enable: true
      acl: [acl_solution]
    smarty:
      template: %modules.solution.path%template/
      compile:  %path.smarty.compile%          